sonar.organization=singhvipul2200
sonar.projectKey=singhvipul2200_mern-ecommerce-k8s-github-actions

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.test.jsx

# Helps Sonar map issues back to the right lines in JS/JSX files
sonar.sourceEncoding=UTF-8