apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9qYWNrc29uc2luZ2g1OTRfZGJfdXNlcjpDZm1XSm9IMk9kNDNLdmhNQGNsdXN0ZXIwLnJrM2RwYXAubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  UPSTASH_REDIS_URL: cmVkaXNzOi8vZGVmYXVsdDpnUUFBQUFBQUFhWk1BQUlnY0RFMll6VTVZVEV5TURJeU5tVTBPR0V5T1RabFl6RTNNR001TWpoall6UmxZUUBwb3B1bGFyLXRhZHBvbGUtMTA4MTA4LnVwc3Rhc2guaW86NjM3OS8w
  ACCESS_TOKEN_SECRET: NmQzYTA0M2U3OGU2NWJlMTc2MGY5ODRlZjRjOWYwMzA1ZTNkY2E3ZTcyODBmYWNmZWU5NzNlZWI5OTZlMTQzZTc1OTNjMjI2MWIwYWRiM2M1ZmMxNjlmMWI3YzVkNmM2MjU4NTFmMWI0NTZjMGY1ZjVjMWQyNGUxMWFlNDhlNTA=
  REFRESH_TOKEN_SECRET: NTJkOTAzNThjNjE3M2IwODc2NTZkNDA5MGYzYzFmMjBiODY5NzJiZDY1NzM4NTZhYTdhNDdhMDMyNWM0NmNkMDZjYzM0Yjc3NTgzYWQ3NmU3YWNmYTBhNzdlYzBlZjhkNzI3NzdhYmEzNDA0MDQ3Y2YzZjQ0ZjlkNWEzZWIwMzA=
  CLOUDINARY_CLOUD_NAME: a3Jmc3pudHk=
  CLOUDINARY_API_KEY: NzIyOTYyNTc5MzM3Mjky
  CLOUDINARY_API_SECRET: MEtpRzVLX1YwVUVmUm1XeVF6VXBzMlJOdHFR
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVU2bVNkMnpmQzAzYVNLUGZxSjkyTVBSVFRIUjRsM1YyaGY1WGdCeVRkaXdrZUNzMkRQODVnTFBJWjU1ZE1Hb09BV3FIeTByaHo3bHlid21mY0tlZ0hsUTAwTkhPTkI5ZTM=
stringData:
  CLIENT_URL: "http://localhost:5173"