backend:
  image:
    repository: vipulsingh2200/mern-ecommerce-backend
    tag: "v6"
  replicas: 3

frontend:
  image:
    repository: vipulsingh2200/mern-ecommerce-frontend
    tag: "v6"
  replicas: 3
